version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/car-to-you
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/car-to-you/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoint.sh
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  redis:
    image: redis:5.0.7

volumes:
  gem_cache:
  db_data:
  node_modules:
