development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: car_to_you_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] %>
