default: &default
  adapter: postgresql
  encoding: unicode
  database: car_to_you
  username: rtoledo
  password: 123456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: car_to_you_test

production:
  url: <%= ENV['DATABASE_URL'] %>
