default: &default
  adapter: mysql2
  encoding: unicode
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE'] %>_test

production:
  url: <%= ENV['DATABASE_URL'] %>
